"use strict";
/** **************************************************************************
 * THIS FILE IS AUTO-GENERATED BY plop
 * Do not manually change
 ** ************************************************************************ */
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
const debug = require("debug")("fsm:controller");
const _ = require("lodash");
const redux_1 = require("redux");
const fsmDefinitions_1 = require("./fsmDefinitions");
const ClosedState_1 = require("./states/ClosedState");
const OpenedState_1 = require("./states/OpenedState");
__export(require("./fsmDefinitions"));
exports.fsmSagas = _.concat(fsmDefinitions_1.fsmTransitionSagas, ClosedState_1.ClosedStateSagas, OpenedState_1.OpenedStateSagas);
exports.initialFsmState = {
    fsm: fsmDefinitions_1.initialStateMachineState,
    ClosedState: ClosedState_1.initialClosedStateState,
    OpenedState: OpenedState_1.initialOpenedStateState
};
exports.fsmStateReducer = redux_1.combineReducers({
    fsm: fsmDefinitions_1.fsmCreateReducer,
    ClosedState: ClosedState_1.fsmClosedStateReducer,
    OpenedState: OpenedState_1.fsmOpenedStateReducer
});
//# sourceMappingURL=index.js.map